flowchart LR
  mission_planning_MissionPlanningModule_can_start_mission["mission_planning.MissionPlanningModule.can_start_mission"] --> mission_planning_MissionPlanningModule_get_mission["mission_planning.MissionPlanningModule.get_mission"]
  mission_planning_MissionPlanningModule_start_mission["mission_planning.MissionPlanningModule.start_mission"] --> mission_planning_MissionPlanningModule_can_start_mission["mission_planning.MissionPlanningModule.can_start_mission"]
  mission_planning_MissionPlanningModule_start_mission["mission_planning.MissionPlanningModule.start_mission"] --> mission_planning_MissionPlanningModule_get_mission["mission_planning.MissionPlanningModule.get_mission"]
  sponsorship_SponsorshipModule_evaluate_contract["sponsorship.SponsorshipModule.evaluate_contract"] --> sponsorship_SponsorshipModule_get_contract["sponsorship.SponsorshipModule.get_contract"]
